[package]
name = "blockchain-learning-platform"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
hyper = "1.5.2"
rocksdb = "0.23.0"
serde = "1.0.217"
serde_json = "1.0.136"
tokio = "1.43.0"
tower-http = "0.6.2"

[workspace]
members = [
  "server",
  "client"
]

